app:
  title: "FlowTrace"
  demo_mode: false
  auto_refresh_interval: 30

auth:
  enabled: true
  secret_key: "flowtrace-super-secret-key-change-me"

jenkins:
  url: "http://localhost:8080"
  username: "23FE10CSE00741"
  token: "115f024c9de06f298dadd3a70a691716ab"
